site_name: Moje projekty
site_author: Kmail Semczuk
site_description: >
  Portfolio moich projektÃ³w z Data Science i AI!

theme:
  name: material

nav:
  - ğŸ  Start: index.md
  - ğŸ“Š Analizy:
      - ğŸŸ¢ Obecny projekt:
          - Titanic: Analizy/Titanic/index.md
      - ğŸ”™ Poprzednie projekty:
          - Iris: Analizy/Iris/index.md
  - ğŸ’» Aplikacje: 
      - PÃ³Å‚maraton: Aplikacje/Maraton/index.md
          


