site_name: Moje projekty
site_author: Kmail Semczuk
site_description: >
  Portfolio moich projektÃ³w z Data Science i AI!

repo_name: KamilSemczuk13/ds_portfolio
repo_url: https://github.com/KamilSemczuk13/ds_portfolio.git

theme:
  name: material

nav:
  - ğŸ  Start: index.md
  - ğŸ“Š Analizy:    
     - ğŸ›³ï¸ Titanic (analiza przeÅ¼ywalnoÅ›ci): Analizy/Titanic/index.md
     - ğŸŒ¸ Iris (klasyfikacja kwiatÃ³w): Analizy/Iris/index.md
  - ğŸ’» Aplikacje: 
      - ğŸƒâ€â™‚ï¸ PÃ³Å‚maraton: Aplikacje/Maraton/index.md
      - âœˆï¸ Flight4u â€“ wyszukiwanie lotÃ³w: Aplikacje/Loty/index.md

#- ğŸŸ¢ Obecny projekt: - ğŸ”™ Poprzednie projekty:


